export const TODOS_REDUCER_NAME = 'TODOS_REDUCER';
export const DELETE_TODO_SAGA_NAME = 'DELETE_TODO_SAGA_NAME';
export const MARK_TODO_SAGA_NAME = 'MARK_TODO_SAGA_NAME';
export const UNMARK_TODO_SAGA_NAME = 'UNMARK_TODO_SAGA_NAME';
